/*
 * Circular Countdown v2.3
 *
 * Copyright 2013-2019, LambertGroup
 *
 */

 (function(e){function z(a,c){a.remainingDays=Math.floor(a.totalRemainingSeconds/a.secondsInADay);a.remainingHours=Math.floor((a.totalRemainingSeconds-a.remainingDays*a.secondsInADay)/a.secondsInAnHour);a.remainingMinutes=Math.floor((a.totalRemainingSeconds-a.remainingDays*a.secondsInADay-a.remainingHours*a.secondsInAnHour)/a.secondsInAMinute);a.remainingSeconds=a.totalRemainingSeconds-a.remainingDays*a.secondsInADay-a.remainingHours*a.secondsInAnHour-a.remainingMinutes*a.secondsInAMinute}function r(a,
 c,f,m,k,l,p,d,g,q,r,x,y,w,h){if(0<=d.totalRemainingSeconds){switch(a){case "seconds":var n=2*(60-d.remainingSeconds)*Math.PI/60-.5*Math.PI;d.secondsNumberDiv.html(d.remainingSeconds);break;case "minutes":n=2*(60-d.remainingMinutes)*Math.PI/60-.5*Math.PI;d.minutesNumberDiv.html(d.remainingMinutes);break;case "hours":n=2*(24-d.remainingHours)*Math.PI/24-.5*Math.PI;d.hoursNumberDiv.html(d.remainingHours);break;case "days":n=2*(d.entireWorkingDaysPeriod-d.remainingDays)*Math.PI/d.entireWorkingDaysPeriod-
 .5*Math.PI;d.daysNumberDiv.html(d.remainingDays);break;default:n=2*(60-d.remainingSeconds)*Math.PI/60-.5*Math.PI}"days"==a&&h&&E(g,d,q,r,x,y);-1!=w&&9>w||(c.clearRect(0,0,f.width,f.height),c.beginPath(),c.globalAlpha=m/100,c.arc(parseInt((g.circleRadius+(g.circleLineWidth+g.behindCircleLineWidthExpand)/2+g.circleLeftRightPadding)*d.pluginRatio,10),parseInt((g.circleRadius+(g.circleLineWidth+g.behindCircleLineWidthExpand)/2+g.circleTopBottomPadding)*d.pluginRatio,10),parseInt(g.circleRadius*d.pluginRatio,
 10),0,2*Math.PI,!1),c.lineWidth=parseInt((g.circleLineWidth+g.behindCircleLineWidthExpand)*d.pluginRatio,10),c.strokeStyle=k,c.stroke(),c.closePath(),c.beginPath(),c.globalAlpha=l/100,c.arc(parseInt((g.circleRadius+(g.circleLineWidth+g.behindCircleLineWidthExpand)/2+g.circleLeftRightPadding)*d.pluginRatio,10),parseInt((g.circleRadius+(g.circleLineWidth+g.behindCircleLineWidthExpand)/2+g.circleTopBottomPadding)*d.pluginRatio,10),g.circleRadius*d.pluginRatio,-.5*Math.PI,n,!1),c.lineWidth=parseInt(g.circleLineWidth*
 d.pluginRatio,10),c.strokeStyle=p,c.stroke(),c.closePath());"seconds"==a&&d.remainingSeconds--;0>d.remainingSeconds&&z(d,g)}else if("seconds"==a&&0>=d.repetitionNo)if(e.isFunction(g.complete))d.repetitionNo++,clearInterval(d.intervalIDSeconds),g.complete.call(this);else if(g.autoReset24h){resetNo=0;d.totalRemainingSeconds=-1;d.new_nowD=new Date;for(theIntervalNowDate=Date.UTC(d.new_nowD.getFullYear(),d.new_nowD.getMonth(),d.new_nowD.getDate(),d.new_nowD.getHours(),d.new_nowD.getMinutes(),d.new_nowD.getSeconds())/
 1E3-Date.UTC(d.nowD.getFullYear(),d.nowD.getMonth(),d.nowD.getDate(),d.nowD.getHours(),d.nowD.getMinutes(),d.nowD.getSeconds())/1E3;0>d.totalRemainingSeconds;)resetNo++,g.beginDate=g.launchingDate,g.launchingDate+=86400,d.totalRemainingSeconds=""==g.nowDate?g.launchingDate-Date.UTC(d.new_nowD.getFullYear(),d.new_nowD.getMonth(),d.new_nowD.getDate(),d.new_nowD.getHours(),d.new_nowD.getMinutes(),d.new_nowD.getSeconds())/1E3:g.launchingDate-(Date.UTC(parseInt(nowDate_arr[0],10),parseInt(nowDate_arr[1],
 10)-1,parseInt(nowDate_arr[2],10),parseInt(nowDate_arr[3],10),parseInt(nowDate_arr[4],10),parseInt(nowDate_arr[5],10))/1E3+theIntervalNowDate);d.entireWorkingDaysPeriod=Math.floor((g.launchingDate-g.beginDate)/d.secondsInADay);z(d,g)}}function E(a,c,f,m,k,l){e(".innerNumber",f).css({display:"block",left:parseInt((c.canvasWidth-e(".innerNumber",f).width())/2,10)+"px",top:parseInt((c.canvasHeight-e(".innerNumber",f).height())/2-a.numberAdditionalTopPadding,10)+"px"});e(".innerNumber",m).css({display:"block",
 left:parseInt((c.canvasWidth-e(".innerNumber",m).width())/2,10)+"px",top:parseInt((c.canvasHeight-e(".innerNumber",m).height())/2-a.numberAdditionalTopPadding,10)+"px"});e(".innerNumber",k).css({display:"block",left:parseInt((c.canvasWidth-e(".innerNumber",k).width())/2,10)+"px",top:parseInt((c.canvasHeight-e(".innerNumber",k).height())/2-a.numberAdditionalTopPadding,10)+"px"});e(".innerNumber",l).css({display:"block",left:parseInt((c.canvasWidth-e(".innerNumber",l).width())/2,10)+"px",top:parseInt((c.canvasHeight-
 e(".innerNumber",l).height())/2-a.numberAdditionalTopPadding,10)+"px"})}function F(a,c,f,m,k,l,p,d,g,q,r,x,y){var w=C();responsiveWidth=f.parent().parent().width();c.origWidth!=responsiveWidth&&(responsiveWidth>c.origWidth&&(responsiveWidth=c.origWidth),c.origWidth>responsiveWidth||c.prevOrigWidth!=responsiveWidth)&&(c.prevOrigWidth=responsiveWidth,a.pluginRatio=responsiveWidth/c.origWidth,a.canvasWidth=parseInt(a.canvasOrigWidth*a.pluginRatio,10),a.canvasHeight=parseInt(a.canvasOrigHeight*a.pluginRatio,
 10),a.canvasDays.width=a.canvasWidth,a.canvasDays.height=a.canvasHeight,k.css({width:parseInt(a.unitDivOrigWidthDays*a.pluginRatio,10)+"px",height:parseInt(a.unitDivOrigHeightDays*a.pluginRatio,10)+"px"}),a.canvasHours.width=a.canvasWidth,a.canvasHours.height=a.canvasHeight,l.css({width:parseInt(a.unitDivOrigWidthHours*a.pluginRatio,10)+"px",height:parseInt(a.unitDivOrigHeightHours*a.pluginRatio,10)+"px"}),a.canvasMinutes.width=a.canvasWidth,a.canvasMinutes.height=a.canvasHeight,p.css({width:parseInt(a.unitDivOrigWidthMinutes*
 a.pluginRatio,10)+"px",height:parseInt(a.unitDivOrigHeightMinutes*a.pluginRatio,10)+"px"}),a.canvasSeconds.width=a.canvasWidth,a.canvasSeconds.height=a.canvasHeight,d.css({width:parseInt(a.unitDivOrigWidthSeconds*a.pluginRatio,10)+"px",height:parseInt(a.unitDivOrigHeightSeconds*a.pluginRatio,10)+"px"}),text_top_aux=0,-1!=w&&9>w&&(text_top_aux=a.canvasHeight),e(".innerNumber",k).css({"font-size":parseInt(c.numberSize*a.pluginRatio,10)+"px","line-height":parseInt(c.numberSize*a.pluginRatio,10)+"px"}),
 e(".innerText",k).css({top:text_top_aux+"px","font-size":parseInt(c.textSize*a.pluginRatio,10)+"px","line-height":parseInt(c.textSize*a.pluginRatio,10)+"px","margin-top":parseInt(c.textMarginTop*a.pluginRatio,10)+"px","padding-top":parseInt(c.textPadding*a.pluginRatio,10)+"px","padding-bottom":parseInt(c.textPadding*a.pluginRatio,10)+"px"}),e(".innerNumber",l).css({"font-size":parseInt(c.numberSize*a.pluginRatio,10)+"px","line-height":parseInt(c.numberSize*a.pluginRatio,10)+"px"}),e(".innerText",
 l).css({top:text_top_aux+"px","font-size":parseInt(c.textSize*a.pluginRatio,10)+"px","line-height":parseInt(c.textSize*a.pluginRatio,10)+"px","margin-top":parseInt(c.textMarginTop*a.pluginRatio,10)+"px","padding-top":parseInt(c.textPadding*a.pluginRatio,10)+"px","padding-bottom":parseInt(c.textPadding*a.pluginRatio,10)+"px"}),e(".innerNumber",p).css({"font-size":parseInt(c.numberSize*a.pluginRatio,10)+"px","line-height":parseInt(c.numberSize*a.pluginRatio,10)+"px"}),e(".innerText",p).css({top:text_top_aux+
 "px","font-size":parseInt(c.textSize*a.pluginRatio,10)+"px","line-height":parseInt(c.textSize*a.pluginRatio,10)+"px","margin-top":parseInt(c.textMarginTop*a.pluginRatio,10)+"px","padding-top":parseInt(c.textPadding*a.pluginRatio,10)+"px","padding-bottom":parseInt(c.textPadding*a.pluginRatio,10)+"px"}),e(".innerNumber",d).css({"font-size":parseInt(c.numberSize*a.pluginRatio,10)+"px","line-height":parseInt(c.numberSize*a.pluginRatio,10)+"px"}),e(".innerText",d).css({top:text_top_aux+"px","font-size":parseInt(c.textSize*
 a.pluginRatio,10)+"px","line-height":parseInt(c.textSize*a.pluginRatio,10)+"px","margin-top":parseInt(c.textMarginTop*a.pluginRatio,10)+"px","padding-top":parseInt(c.textPadding*a.pluginRatio,10)+"px","padding-bottom":parseInt(c.textPadding*a.pluginRatio,10)+"px"}),g.css({width:parseInt(c.origWidth*a.pluginRatio,10)+2+"px","margin-top":parseInt(c.allCirclesTopMargin*a.pluginRatio,10)+"px","margin-bottom":parseInt(c.allCirclesBottomMargin*a.pluginRatio,10)+"px"}),r.css({"font-family":c.pluginFontFamily+
 " !important","font-size":Math.max(10,parseInt(c.h2Size*a.pluginRatio,10))+"px !important","line-height":Math.max(10,parseInt(c.h2Size*a.pluginRatio,10))+"px !important","margin-top":Math.max(10,parseInt(c.h2TopMargin*a.pluginRatio,10))+"px !important"}),x.css({"font-family":c.pluginFontFamily+" !important","font-size":Math.max(8,parseInt(c.h3Size*a.pluginRatio,10))+"px !important","line-height":Math.max(8,parseInt(c.h3Size*a.pluginRatio,10))+"px !important","margin-top":parseInt(c.h3TopMargin*a.pluginRatio,
 10)+"px !important"}),y.css({"font-family":c.pluginFontFamily+" !important","font-size":Math.max(6,parseInt(c.h4Size*a.pluginRatio,10))+"px !important","line-height":Math.max(6,parseInt(c.h4Size*a.pluginRatio,10))+"px !important","margin-top":parseInt(c.h4TopMargin*a.pluginRatio,10)+"px !important"}),m.css({width:parseInt(c.origWidth*a.pluginRatio,10)+"px"}),q.css({width:parseInt(c.origWidth*a.pluginRatio,10)+"px"}))}function C(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&
 (a=parseFloat(RegExp.$1));return parseInt(a,10)}function q(a){var c=!1;a=a.substr(a.length-4).toLowerCase();if(".jpg"==a||".png"==a||".gif"==a)c=!0;return c}e.fn.circularCountdown=function(a){a=e.extend({},e.fn.circularCountdown.defaults,a);return this.each(function(){var c=e(this),f=e("<div></div>").addClass("circularCountdown").addClass(a.type);c.wrap(f);var m=c.parent(".circularCountdown"),k=e(".secondsDiv",m),l=e(".minutesDiv",m),p=e(".hoursDiv",m),d=e(".daysDiv",m),g=e(".theCircles",m);c=e(".socialIcons",
 m);var A=e(".socialIconsDiv",m),B=e(".logoDiv",m),x=e("h2",m),y=e("h3",m),w=e("h4",m),h="",n=f=f="",t="",u="",v=C();m.css({"font-family":a.pluginFontFamily+" !important"});f=a.beginDate.split(",");n=a.launchingDate.split(",");a.beginDate=Date.UTC(parseInt(f[0],10),parseInt(f[1],10)-1,parseInt(f[2],10),parseInt(f[3],10),parseInt(f[4],10),parseInt(f[5],10))/1E3;a.launchingDate=Date.UTC(parseInt(n[0],10),parseInt(n[1],10)-1,parseInt(n[2],10),parseInt(n[3],10),parseInt(n[4],10),parseInt(n[5],10))/1E3;
 var b={nowD:new Date,secondsInADay:86400,secondsInAnHour:3600,secondsInAMinute:60,entireWorkingDaysPeriod:0,totalRemainingSeconds:0,remainingDays:0,remainingHours:0,remainingMinutes:0,remainingSeconds:0,canvasSeconds:"",ctxSeconds:"",secondsNumberDiv:e(".innerNumber",k),canvasMinutes:"",ctxMinutes:"",minutesNumberDiv:e(".innerNumber",l),canvasHours:"",ctxHours:"",hoursNumberDiv:e(".innerNumber",p),canvasDays:"",ctxDays:"",daysNumberDiv:e(".innerNumber",d),canvasWidth:0,canvasOrigWidth:0,canvasHeight:0,
 canvasOrigHeight:0,unitDivOrigWidth:0,unitDivOrigHeight:0,unitDivOrigWidthDays:0,unitDivOrigHeightDays:0,unitDivOrigWidthHours:0,unitDivOrigHeightHours:0,unitDivOrigWidthMinutes:0,unitDivOrigHeightMinutes:0,unitDivOrigWidthSeconds:0,unitDivOrigHeightSeconds:0,pluginRatio:1,repetitionNo:0};b.entireWorkingDaysPeriod=Math.floor((a.launchingDate-a.beginDate)/b.secondsInADay);nowDate_arr=a.nowDate.split(",");b.totalRemainingSeconds=""==a.nowDate?a.launchingDate-Date.UTC(b.nowD.getFullYear(),b.nowD.getMonth(),
 b.nowD.getDate(),b.nowD.getHours(),b.nowD.getMinutes(),b.nowD.getSeconds())/1E3:a.launchingDate-Date.UTC(parseInt(nowDate_arr[0],10),parseInt(nowDate_arr[1],10)-1,parseInt(nowDate_arr[2],10),parseInt(nowDate_arr[3],10),parseInt(nowDate_arr[4],10),parseInt(nowDate_arr[5],10))/1E3;z(b,a);b.canvasWidth=2*a.circleRadius+a.circleLineWidth+a.behindCircleLineWidthExpand+2*a.circleLeftRightPadding;b.canvasHeight=2*a.circleRadius+a.circleLineWidth+a.behindCircleLineWidthExpand+2*a.circleTopBottomPadding;b.canvasOrigWidth=
 b.canvasWidth;b.canvasOrigHeight=b.canvasHeight;-1!=v&&9>v||(b.canvasDays=e(".canvasDays",m)[0],b.canvasDays.width=b.canvasWidth,b.canvasDays.height=b.canvasHeight,b.ctxDays=b.canvasDays.getContext("2d"),r("days",b.ctxDays,b.canvasDays,a.behindCircleAlphaDays,a.behindCircleColorDays,a.circleAlphaDays,a.circleColorDays,b,a,d,p,l,k,v,0),b.canvasHours=e(".canvasHours",m)[0],b.canvasHours.width=b.canvasWidth,b.canvasHours.height=b.canvasHeight,b.ctxHours=b.canvasHours.getContext("2d"),r("hours",b.ctxHours,
 b.canvasHours,a.behindCircleAlphaHours,a.behindCircleColorHours,a.circleAlphaHours,a.circleColorHours,b,a,d,p,l,k,v,0),b.canvasMinutes=e(".canvasMinutes",m)[0],b.canvasMinutes.width=b.canvasWidth,b.canvasMinutes.height=b.canvasHeight,b.ctxMinutes=b.canvasMinutes.getContext("2d"),r("minutes",b.ctxMinutes,b.canvasMinutes,a.behindCircleAlphaMinutes,a.behindCircleColorMinutes,a.circleAlphaMinutes,a.circleColorMinutes,b,a,d,p,l,k,v,0),b.canvasSeconds=e(".canvasSeconds",m)[0],b.canvasSeconds.width=b.canvasWidth,
 b.canvasSeconds.height=b.canvasHeight,b.ctxSeconds=b.canvasSeconds.getContext("2d"),r("seconds",b.ctxSeconds,b.canvasSeconds,a.behindCircleAlphaSeconds,a.behindCircleColorSeconds,a.circleAlphaSeconds,a.circleColorSeconds,b,a,d,p,l,k,v,0));b.totalRemainingSeconds--;b.intervalIDSeconds=setInterval(function(){b.totalRemainingSeconds--;r("seconds",b.ctxSeconds,b.canvasSeconds,a.behindCircleAlphaSeconds,a.behindCircleColorSeconds,a.circleAlphaSeconds,a.circleColorSeconds,b,a,d,p,l,k,v,1);r("minutes",b.ctxMinutes,
 b.canvasMinutes,a.behindCircleAlphaMinutes,a.behindCircleColorMinutes,a.circleAlphaMinutes,a.circleColorMinutes,b,a,d,p,l,k,v,1);r("hours",b.ctxHours,b.canvasHours,a.behindCircleAlphaHours,a.behindCircleColorHours,a.circleAlphaHours,a.circleColorHours,b,a,d,p,l,k,v,1);r("days",b.ctxDays,b.canvasDays,a.behindCircleAlphaDays,a.behindCircleColorDays,a.circleAlphaDays,a.circleColorDays,b,a,d,p,l,k,v,1)},1E3);h=a.divBackgroundDays;q(a.divBackgroundDays)&&(h="url("+a.divBackgroundDays+")");f=0;""!=a.borderTopColorDays&&
 (f="1px solid "+a.borderTopColorDays);n=0;""!=a.borderRightColorDays&&(n="1px solid "+a.borderRightColorDays);t=0;""!=a.borderBottomColorDays&&(t="1px solid "+a.borderBottomColorDays);u=0;""!=a.borderLeftColorDays&&(u="1px solid "+a.borderLeftColorDays);d.css({"border-top":f,"border-right":n,"border-bottom":t,"border-left":u,background:h});h=a.divBackgroundHours;q(a.divBackgroundHours)&&(h="url("+a.divBackgroundHours+")");f=0;""!=a.borderTopColorHours&&(f="1px solid "+a.borderTopColorHours);n=0;""!=
 a.borderRightColorHours&&(n="1px solid "+a.borderRightColorHours);t=0;""!=a.borderBottomColorHours&&(t="1px solid "+a.borderBottomColorHours);u=0;""!=a.borderLeftColorHours&&(u="1px solid "+a.borderLeftColorHours);p.css({"border-top":f,"border-right":n,"border-bottom":t,"border-left":u,background:h});h=a.divBackgroundMinutes;q(a.divBackgroundMinutes)&&(h="url("+a.divBackgroundMinutes+")");f=0;""!=a.borderTopColorMinutes&&(f="1px solid "+a.borderTopColorMinutes);n=0;""!=a.borderRightColorMinutes&&
 (n="1px solid "+a.borderRightColorMinutes);t=0;""!=a.borderBottomColorMinutes&&(t="1px solid "+a.borderBottomColorMinutes);u=0;""!=a.borderLeftColorMinutes&&(u="1px solid "+a.borderLeftColorMinutes);l.css({"border-top":f,"border-right":n,"border-bottom":t,"border-left":u,background:h});h=a.divBackgroundSeconds;q(a.divBackgroundSeconds)&&(h="url("+a.divBackgroundSeconds+")");f=0;""!=a.borderTopColorSeconds&&(f="1px solid "+a.borderTopColorSeconds);n=0;""!=a.borderRightColorSeconds&&(n="1px solid "+
 a.borderRightColorSeconds);t=0;""!=a.borderBottomColorSeconds&&(t="1px solid "+a.borderBottomColorSeconds);u=0;""!=a.borderLeftColorSeconds&&(u="1px solid "+a.borderLeftColorSeconds);k.css({"border-top":f,"border-right":n,"border-bottom":t,"border-left":u,background:h});b.unitDivOrigWidthDays=parseInt(2*a.circleRadius+a.circleLineWidth+a.behindCircleLineWidthExpand+2*a.circleLeftRightPadding,10);b.unitDivOrigWidth=b.unitDivOrigWidthDays;b.unitDivOrigWidthHours=b.unitDivOrigWidthDays;b.unitDivOrigWidthMinutes=
 b.unitDivOrigWidthDays;b.unitDivOrigWidthSeconds=b.unitDivOrigWidthDays;""!=a.borderLeftColorDays&&b.unitDivOrigWidthDays--;""!=a.borderRightColorDays&&b.unitDivOrigWidthDays--;d.css({width:b.unitDivOrigWidth+"px"});""!=a.borderLeftColorHours&&b.unitDivOrigWidthHours--;""!=a.borderRightColorHours&&b.unitDivOrigWidthHours--;p.css({width:b.unitDivOrigWidth+"px"});""!=a.borderLeftColorMinutes&&b.unitDivOrigWidthMinutes--;""!=a.borderRightColorMinutes&&b.unitDivOrigWidthMinutes--;l.css({width:b.unitDivOrigWidth+
 "px"});""!=a.borderLeftColorSeconds&&b.unitDivOrigWidthSeconds--;""!=a.borderRightColorSeconds&&b.unitDivOrigWidthSeconds--;k.css({width:b.unitDivOrigWidth+"px"});f=0;-1!=v&&9>v&&(f=b.canvasHeight);e(".innerNumber",d).css({color:a.numberColorDays,"font-size":a.numberSize+"px","line-height":a.numberSize+"px"});h=a.textColorBackgroundDays;q(a.textColorBackgroundDays)&&(h="url("+a.textColorBackgroundDays+")");e(".innerText",d).css({top:f+"px",color:a.textColorDays,"font-size":a.textSize+"px","line-height":a.textSize+
 "px","margin-top":a.textMarginTop+"px","padding-top":a.textPadding+"px","padding-bottom":a.textPadding+"px",background:h});e(".innerNumber",p).css({color:a.numberColorHours,"font-size":a.numberSize+"px","line-height":a.numberSize+"px"});h=a.textColorBackgroundHours;q(a.textColorBackgroundHours)&&(h="url("+a.textColorBackgroundHours+")");e(".innerText",p).css({top:f+"px",color:a.textColorHours,"font-size":a.textSize+"px","line-height":a.textSize+"px","margin-top":a.textMarginTop+"px","padding-top":a.textPadding+
 "px","padding-bottom":a.textPadding+"px",background:h});e(".innerNumber",l).css({color:a.numberColorMinutes,"font-size":a.numberSize+"px","line-height":a.numberSize+"px"});h=a.textColorBackgroundMinutes;q(a.textColorBackgroundMinutes)&&(h="url("+a.textColorBackgroundMinutes+")");e(".innerText",l).css({top:f+"px",color:a.textColorMinutes,"font-size":a.textSize+"px","line-height":a.textSize+"px","margin-top":a.textMarginTop+"px","padding-top":a.textPadding+"px","padding-bottom":a.textPadding+"px",background:h});
 e(".innerNumber",k).css({color:a.numberColorSeconds,"font-size":a.numberSize+"px","line-height":a.numberSize+"px"});h=a.textColorBackgroundSeconds;q(a.textColorBackgroundSeconds)&&(h="url("+a.textColorBackgroundSeconds+")");e(".innerText",k).css({top:f+"px",color:a.textColorSeconds,"font-size":a.textSize+"px","line-height":a.textSize+"px","margin-top":a.textMarginTop+"px","padding-top":a.textPadding+"px","padding-bottom":a.textPadding+"px",background:h});f=parseInt(k.width()+l.width()+p.width()+d.width(),
 10);""!=a.borderLeftColorDays&&f++;""!=a.borderRightColorDays&&f++;""!=a.borderLeftColorHours&&f++;""!=a.borderRightColorHours&&f++;""!=a.borderLeftColorMinutes&&f++;""!=a.borderRightColorMinutes&&f++;""!=a.borderLeftColorSeconds&&f++;""!=a.borderRightColorSeconds&&f++;a.origWidth=f;a.prevOrigWidth=f;g.css({width:f+2+"px","margin-top":a.allCirclesTopMargin+"px","margin-bottom":a.allCirclesBottomMargin+"px"});x.css({"font-family":a.pluginFontFamily+" !important","font-size":a.h2Size+"px !important",
 "line-height":a.h2Size+"px !important",color:a.h2Color+" !important","font-weight":a.h2Weight+" !important","margin-top":a.h2TopMargin+"px !important"});y.css({"font-family":a.pluginFontFamily+" !important","font-size":a.h3Size+"px !important","line-height":a.h3Size+"px !important",color:a.h3Color+" !important","font-weight":a.h3Weight+" !important","margin-top":a.h3TopMargin+"px !important"});w.css({"font-family":a.pluginFontFamily+" !important","font-size":a.h4Size+"px !important","line-height":a.h4Size+
 "px !important",color:a.h4Color+" !important","font-weight":a.h4Weight+" !important","margin-top":a.h4TopMargin+"px !important"});B.css({width:f+"px",background:"url("+a.lineSeparatorImg+") bottom left repeat-x"});A.css({width:f+"px",background:"url("+a.lineSeparatorImg+") top left repeat-x"});h=a.socialBgOFF;q(a.socialBgOFF)&&(h="url("+a.socialBgOFF+") no-repeat");e("li",c).css({background:h});e("li",c).on("mouseover",function(){h=a.socialBgON;q(a.socialBgON)&&(h="url("+a.socialBgON+") no-repeat");
 e(this).css({background:h})});e("li",c).on("mouseout",function(){h=a.socialBgOFF;q(a.socialBgOFF)&&(h="url("+a.socialBgOFF+") no-repeat");e(this).css({background:h})});b.unitDivOrigHeightDays=parseInt(2*a.circleRadius+a.circleLineWidth+a.behindCircleLineWidthExpand+2*a.circleTopBottomPadding+e(".innerText",d).height()+2*a.textPadding+a.textMarginTop,10);b.unitDivOrigHeight=b.unitDivOrigHeightDays;b.unitDivOrigHeightHours=b.unitDivOrigHeightDays;b.unitDivOrigHeightMinutes=b.unitDivOrigHeightDays;b.unitDivOrigHeightSeconds=
 b.unitDivOrigHeightDays;""!=a.borderTopColorDays&&b.unitDivOrigHeightDays--;""!=a.borderBottomColorDays&&b.unitDivOrigHeightDays--;d.css({height:b.unitDivOrigHeight+"px"});""!=a.borderTopColorHours&&b.unitDivOrigHeightHours--;""!=a.borderBottomColorHours&&b.unitDivOrigHeightHours--;p.css({height:b.unitDivOrigHeight+"px"});""!=a.borderTopColorMinutes&&b.unitDivOrigHeightMinutes--;""!=a.borderBottomColorMinutes&&b.unitDivOrigHeightMinutes--;l.css({height:b.unitDivOrigHeight+"px"});""!=a.borderTopColorSeconds&&
 b.unitDivOrigHeightSeconds--;""!=a.borderBottomColorSeconds&&b.unitDivOrigHeightSeconds--;k.css({height:b.unitDivOrigHeight+"px"});setTimeout(function(){E(a,b,d,p,l,k)},200);a.responsive&&F(b,a,m,B,d,p,l,k,g,A,x,y,w);var D=!1;e(window).on("resize",function(){var c=C();doResizeNow=!0;-1!=c&&9==c&&0==b.windowWidth&&(doResizeNow=!1);b.windowWidth==e(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,
 doResizeNow=!0)):b.windowWidth=e(window).width();a.responsive&&doResizeNow&&(!1!==D&&clearTimeout(D),D=setTimeout(function(){F(b,a,m,B,d,p,l,k,g,A,x,y,w)},300))})})};e.fn.circularCountdown.defaults={type:"version1",beginDate:"2014,2,30,22,30,10",launchingDate:"2018,8,30,14,12,10",nowDate:"",pluginFontFamily:"'PT Serif', serif",circleRadius:85,circleLineWidth:20,behindCircleLineWidthExpand:6,circleTopBottomPadding:20,circleLeftRightPadding:30,numberSize:60,numberAdditionalTopPadding:2,textSize:24,
 textMarginTop:18,textPadding:15,lineSeparatorImg:"circular_countdown_images/line.png",allCirclesTopMargin:0,allCirclesBottomMargin:80,divBackgroundDays:"",borderTopColorDays:"",borderRightColorDays:"",borderBottomColorDays:"",borderLeftColorDays:"",circleColorDays:"#dd1e2f",circleAlphaDays:100,behindCircleColorDays:"#000000",behindCircleAlphaDays:30,numberColorDays:"#FFFFFF",textColorDays:"#6f6f6f",textColorBackgroundDays:"",divBackgroundHours:"",borderTopColorHours:"",borderRightColorHours:"",borderBottomColorHours:"",
 borderLeftColorHours:"",circleColorHours:"#ebb035",circleAlphaHours:100,behindCircleColorHours:"#000000",behindCircleAlphaHours:30,numberColorHours:"#FFFFFF",textColorHours:"#6f6f6f",textColorBackgroundHours:"",divBackgroundMinutes:"",borderTopColorMinutes:"",borderRightColorMinutes:"",borderBottomColorMinutes:"",borderLeftColorMinutes:"",circleColorMinutes:"#06a2cb",circleAlphaMinutes:100,behindCircleColorMinutes:"#000000",behindCircleAlphaMinutes:30,numberColorMinutes:"#FFFFFF",textColorMinutes:"#6f6f6f",
 textColorBackgroundMinutes:"",divBackgroundSeconds:"",borderTopColorSeconds:"",borderRightColorSeconds:"",borderBottomColorSeconds:"",borderLeftColorSeconds:"",circleColorSeconds:"#218559",circleAlphaSeconds:100,behindCircleColorSeconds:"#000000",behindCircleAlphaSeconds:30,numberColorSeconds:"#FFFFFF",textColorSeconds:"#6f6f6f",textColorBackgroundSeconds:"",socialBgOFF:"circular_countdown_images/social_icons/socialCircleOFF.png",socialBgON:"circular_countdown_images/social_icons/socialCircleON.png",
 h2Size:36,h2Color:"#FFFFFF",h2Weight:"bold",h2TopMargin:60,h3Size:24,h3Color:"#6f6f6f",h3Weight:"normal",h3TopMargin:0,h4Size:14,h4Color:"#6f6f6f",h4Weight:"normal",h4TopMargin:15,complete:null,autoReset24h:!1,responsive:!0,origWidth:0,prevOrigWidth:0,thumbsWrapperMarginBottom:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
